services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: escola
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 15

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django_backend
    entrypoint: ["sh", "-c", "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    environment:
      DB_HOST: db
      DB_NAME: escola
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
